### ISSUE TITLE
feature request: list my repositories sorted by star count

### ISSUE THREAD

**Issue by andrewrk** [melissanoelle/hubflow#1]
I'm not sure if this fits into your project or not but that's something I've wanted for a while. Maybe it could be the way that the user chooses which project to triage?

**Comment by malakada** [comment]
Duplicate of #2.

**Comment by malakada** [comment]
![trollface](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB3e9fnboPhVaB0UY9imBPPScq3_DqHojn2Te8GXhqdyYfGYOoNbyQBMg)
